name: Deploy LMS Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (local copy)
        uses: actions/checkout@v3

      - name: Setup SSH Agent for EC2
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
            # Prepare directory
            sudo mkdir -p /var/www/html/LMS-Course-API
            sudo chown -R ubuntu:ubuntu /var/www/html/LMS-Course-API

            # Clone or update using SSH (must have SSH key on EC2)
            if [ ! -d /var/www/html/LMS-Course-API/.git ]; then
              git clone git@github.com:<your-username>/LMS-Course-API.git /var/www/html/LMS-Course-API
            else
              cd /var/www/html/LMS-Course-API
              git reset --hard
              git pull origin main
            fi

            # Install dependencies
            cd /var/www/html/LMS-Course-API
            npm install

            # Restart backend service
            sudo systemctl restart lms-backend

            # Optional: check service status
            sudo systemctl status lms-backend --no-pager
          EOF
