name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 43.205.138.179
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Navigating to deployment directory..."
          cd /var/www/html

          if [ ! -d "LMS-Course-API" ]; then
            echo "Cloning repository for the first time..."
            git clone git@github.com:vulture-lines/LMS-Course-API.git
          fi

          cd LMS-Course-API

          echo "Resetting local changes and pulling latest code..."
          git reset --hard
          git pull origin main

          echo "Installing dependencies..."
          npm install

          echo "Restarting backend with PM2..."
          pm2 restart lms-backend || pm2 start index.js --name lms-backend
